### ISSUE TITLE
Module Utils: ACIModule.get_diff() enhancemnt

### ISSUE THREAD

**Issue by jmcgill298** [datacenter/aci-ansible#43]
I noticed that I added the object's name into the updated config body. This was an oversight from how I had to build requests from another API I have been working with for the last month, but we should not need it as long as we are including the object's name in the URL path.

Line 306 in aci.py
`config["name"] = proposed_config["name"]`

**Comment by dagwieers** [comment]
I hope this is now fixed ?

**Comment by jmcgill298** [comment]
This is not fixed as we need to double check all modules are using the full URL (you could also end the URL at the object before the object being created/updated, and that would require the "name" key. This is not a critical issue, just cleaning things up a bit.
